### ISSUE TITLE
Fails to load Gruntfile.js after calling setBase

### ISSUE THREAD

**Issue by ThaNarie** [vladikoff/grunt-devtools#10]
In our project structure, we have the grunt-files in a seperate folder (tools/build/), and we set the base after loading all the tasks:
grunt.file.setBase('../../');

Because of this, the devtools task cannot find the Gruntfile.js

Could this path be added to a devtools-configuration-section (just like configuring other grunt tasks)?

**Comment by vladikoff** [comment]
Thanks for reporting this!
I'll take a look at this tomorrow

**Comment by vladikoff** [comment]
Fixed https://github.com/vladikoff/grunt-devtools/tree/dev and will ship with `0.2.0`.
Please check the test project structure https://github.com/vladikoff/grunt-devtools/tree/dev/test/basePath
