### ISSUE TITLE
Alias tasks

### ISSUE THREAD

**Issue by jeandat** [vladikoff/grunt-devtools#13]
Hello,

Does the alias tasks section works ?

It seems that all tasks (alias or not) are listed under task. Did I miss something ? Is there something special to do to help the plugin ?

**Comment by vladikoff** [comment]
@jan4dev Hey, could you take a screenshot?

**Comment by jeandat** [comment]
Voila.
![capture decran 2013-08-06 a 20 13 31](https://f.cloud.github.com/assets/2780462/919160/01da9c94-fec4-11e2-98e3-014113827be4.png)

**Comment by vladikoff** [comment]
@jan4dev Thanks for the screenshot! 
Good news: issues like this are fixed in 0.2.0
Bad news: 0.2.0 is not out yet, but will be out very soon. I will close this issue when 0.2.0 is out and let you know :)
Hopefully you can still use this for now even though the tasks are not listed properly.

**Comment by jeandat** [comment]
Glad to hear it. Waiting for it then. Thanks for your plugin, it is very practical.

**Comment by vladikoff** [comment]
Alias tasks should be fixed! 0.2.0 landed, update your plugins and modules :) 
Also see global install

**Comment by jeandat** [comment]
Good news. That's really a plus. Thanks a lot.

2013/9/17 Vlad Filippov notifications@github.com
