### ISSUE TITLE
Doesn't recognize Gruntfile.coffee

### ISSUE THREAD

**Issue by kasperisager** [vladikoff/grunt-devtools#2]
First off, I absolutely love this extension! However, the devtools task doesn't recognize the Gruntfile if it's written in CoffeeScript:

```
Warning: ENOENT, no such file or directory 'Gruntfile.js' Use --force to continue.
```

**Comment by vladikoff** [comment]
Thanks for filing this issue.
I Will add 'Gruntfile.cofee' support as soon as possible.

**Comment by kasperisager** [comment]
Awesome, thanks! This is a pretty meta workaround for the time being:

```
coffee:
    gruntfile:
        files: 'Gruntfile.js' : 'Gruntfile.coffee'
```

**Comment by vladikoff** [comment]
Added `Gruntfile.coffee` support in `0.1.0-alpha3`. Pushed to NPM.

Here's a preview of it working with [https://github.com/chaplinjs/chaplin](https://github.com/chaplinjs/chaplin)

![](http://v14d.com/i/512e91b1734f7.png)
