### ISSUE TITLE
Conflict with Anti-Virus

### ISSUE THREAD

**Issue by mattcodez** [vladikoff/grunt-devtools#20]
My employer has Kaspersky anti-virus on our PC's. When installing the npm package for grunt-devtools, I received a report from Kaspersky:
`12/16/2013 9:03:45 AM    Process C:\PROGRAM FILES\NODEJS\NODE.EXE (PID: 16272): Process is trying to redirect data input/output. Probably it is attempt of remote access to your computer (RootShell)`
and then:
`12/16/2013 9:03:46 AM    Process C:\PROGRAM FILES\NODEJS\NODE.EXE (PID: 16272): Source file deleted.`

Yup, it actually deleted Node!  I'm not sure if there's anything that can be done about this, I imagine this is a vital part of how the plug-in works. Thought I would mentioned it anyways though.

**Comment by mattcodez** [comment]
I was able to whitelist Node to get the install to proceed. The more I think about it, the less I feel that devtools should bother being concerned about this at all.

**Comment by vladikoff** [comment]
Thanks for reporting this and I'm happy you resolved this :)
