### ISSUE TITLE
Run npm install before trying to run devtools.

### ISSUE THREAD

**Issue by dechowdev** [vladikoff/grunt-devtools#25]
If you install grunt-devtools in the global namespace, it would be nice that the module installed the modules, from the gruntfile through npm-install instead of simply pushing out an error.
Even if I have grunt installed in a "global" space:

```
npm install -g grunt
```

It gives out this error
![Error](https://f.cloud.github.com/assets/816899/2049027/dec9b3f8-8a59-11e3-90f1-573141538e66.png)

```
Fatal error: Unable to find local grunt.
Failed to find your Gruntfile or 'grunt' node module.
Are you running 'grunt-devtools' in a directory with a Gruntfile?
```

Best
Lucas

**Comment by mapb1990** [comment]
same here:

```
D:\Users\Miguel Borges\Documents\Trabalhos\Projecto\Source Code\portal>grunt-devtools
Failed to find your Gruntfile or 'grunt' node module.
Are you running 'grunt-devtools' in a directory with a Gruntfile?
```

**Comment by vladikoff** [comment]
Thanks for filing this issue.

> Even if I have grunt installed in a "global" space:

That should never be the case. http://gruntjs.com/getting-started#how-the-cli-works

Also, "grunt-devtools"  assumes you have a fully working project. 
If you can properly run `grunt` from your project directory, then you should be able to run `grunt-devtools`. All other options open a variety of edge cases.
