### ISSUE TITLE
Firefox add-on

### ISSUE THREAD

**Issue by nt1m** [vladikoff/grunt-devtools#32]
I'd be nice if you could make a Firefox add-on.

Here's an example of a devtools addon that works both on Firefox and Chrome : 
https://github.com/emberjs/ember-inspector
It uses grunt tasks to generate the chrome addon and the Firefox addon.

Here's a plain Firefox DevTools add-on example : https://github.com/victorporof/Restartless-Template

**Comment by vladikoff** [comment]
https://github.com/deepak1556/grunt-ffdevtools
