### ISSUE TITLE
execvp(): Permission denied

### ISSUE THREAD

**Issue by markparolisi** [vladikoff/grunt-devtools#6]
Any insight into the cause of this error?

**Comment by vladikoff** [comment]
Hey, When do you experience this error? Which task are you running? Which OS? 
Seems like there might be a permission issue

Also make sure to update to the latest version, by doing `npm install grunt-devtools` and also hitting `Update extensions now` in Chrome (under `chrome://extensions/` )

**Comment by vladikoff** [comment]
Also reading this:
http://www.hpc.fsu.edu/index.php?option=com_content&view=article&id=107:make1-execvp-permission-denied&catid=32:compiler-issues&Itemid=48

`attempting to execute a directory, not a program` . Maybe there's a conflict with the naming of the task and the folder in your project?

**Comment by markparolisi** [comment]
Thanks so much for the speedy reply. This was partly my fault and partly the `child_process` module. I use a global Gruntfile for a team-based implementation of Grunt so I have to pass the `--gruntfile` and the `--base`command to `spawn`. Ultimately I ended up with this...

```
  args = [
            '--gruntfile'
            gruntFilePath
            '--base'
            '.'
            msg
  ]
  command = that.spawn('grunt', args)
```

Nothing your project was doing wrong per se. 
Additionally I am writing a standalone webapp using your concept. I spin up a local webserver pointing to a webapp which connects to Grunt via WebSockets. I'll publish my work once it's to a stable state.

Thanks for your work on this.

**Comment by vladikoff** [comment]
Glad you figured it out! 

Regarding the standalone app: if you have time, I would love to hear what you think about this issue, :  [https://github.com/vladikoff/grunt-devtools/issues/3](https://github.com/vladikoff/grunt-devtools/issues/3)
