### ISSUE TITLE
XOR performance will be degraded

### ISSUE THREAD

**Issue by lmartins** [vladikoff/grunt-devtools#8]
Sorry, this isn't an error something i am missing on my config. 
Each time i run devtools i get the following warnings:

→ grunt devtools
Running "devtools" task
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.

> > Grunt Devtools v0.1.0-7 is ready! Proceed to the Chrome extension.

Is there something about this?

Thanks

**Comment by vladikoff** [comment]
Hello, this is a warning from the [WebSocket module](https://github.com/Worlize/WebSocket-Node#current-news) 
Everything should still work, I will research this a bit more and maybe hide the warning. 
It might be the [' building the native extensions'](https://github.com/Worlize/WebSocket-Node#installation) issue.

What OS are you running and what version of Node?

**Comment by lmartins** [comment]
Hi, thanks for the fast reply.
Im on OSX and node v0.8.14

I was just worried that it might affect performance but at this point im very happy with this extension.

Thanks.

**Comment by vladikoff** [comment]
Added some notes on these warnings on the [project wiki](https://github.com/vladikoff/grunt-devtools/wiki#what-are-the-native-modules-not-compiled-warnings-when-i-run-grunt-devtools). Will update it when I have more info.

**Comment by dylanh724** [comment]
There was never a follow-up on this, any word? 2016 and still have this.
